language: android
env:
    - TARGET=android-10 ABI=armeabi
    - TARGET=android-19 ABI=armeabi-v7a
before_install:
    - export TERM=dumb # to get clean gradle output
    - echo no | android create avd --force -n test -t $TARGET -b $ABI
    - emulator -avd test -no-skin -no-audio -no-window &
    - curl -L https://raw.githubusercontent.com/embarkmobile/android-sdk-installer/master/wait_for_emulator | bash
script:
    - ./gradlew --stacktrace lint
    - ./gradlew --stacktrace connectedCheck || (adb logcat -t 100 && false)
    - ./gradlew --stacktrace coveralls
